name: Weader
description: A complete weather forecast app supporting almost every location on planet earth.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  get_it: ^4.0.2
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.7+3
  dartz: ^0.9.1
  http: ^0.12.1
  equatable: ^1.2.0
  geolocator: ^5.3.1
  timezone: ^0.5.7
  intl: ^0.16.1
  transparent_image: ^1.0.0
  uuid: ^2.0.4
  flushbar: ^1.10.4
  flutter_slidable: ^0.5.4
  flare_flutter: ^2.0.3
  package_info: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^5.1.0



flutter:

  uses-material-design: true

  assets:
    - packages/timezone/data/2020a.tzf
    - assets/
    - icons/
